spring:
  application:
    name: employee
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/empdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  thymeleaf:
    cache: false
    mode: HTML
    enabled: true
